/**
 * Build step: write the bot's tool declarations into `dist/src/telegram/catalog-data.js`.
 *
 * Run by `npm run build` after `tsc`, so every deploy, including Workers Builds, ships
 * declarations generated from the exact tools it deploys. See `catalog.ts` for why.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { createServer } from "../server.js";
import { toDeclarations } from "./catalog.js";

const server = createServer();
const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
const client = new Client({ name: "shopping-list-build", version: "1.0.0" });
await Promise.all([server.connect(serverTransport), client.connect(clientTransport)]);

const { tools } = await client.listTools();
const declarations = toDeclarations(tools);
const target = fileURLToPath(new URL("./catalog-data.js", import.meta.url));
writeFileSync(
  target,
  "// Generated by build-catalog.js during `npm run build`. Do not edit.\n" +
    `export const BUILT_CATALOG = ${JSON.stringify(declarations)};\n`
);
console.log(`telegram bot: wrote ${declarations.length} tool declarations`);

await client.close();
await server.close();
